server:
  port: 9999
  context-path: /uaa
  
#the datasource declared in this way is not working
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/oauth2_zuul?createDatabaseIfNotExist=true;
#    username: root
#    password: exito
#    driver-class-name: com.mysql.jdbc.Driver